package model;
// Generated 26 dic 2023 12:32:17 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Artistas generated by hbm2java
 */
public class Artistas implements java.io.Serializable {

	private Integer idArtista;
	private String nombreArtista;
	private Integer edad;
	private Set cancioneses = new HashSet(0);

	public Artistas() {
	}

	public Artistas(String nombreArtista, Integer edad, Set cancioneses) {
		this.nombreArtista = nombreArtista;
		this.edad = edad;
		this.cancioneses = cancioneses;
	}

	public Integer getIdArtista() {
		return this.idArtista;
	}

	public void setIdArtista(Integer idArtista) {
		this.idArtista = idArtista;
	}

	public String getNombreArtista() {
		return this.nombreArtista;
	}

	public void setNombreArtista(String nombreArtista) {
		this.nombreArtista = nombreArtista;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Set getCancioneses() {
		return this.cancioneses;
	}

	public void setCancioneses(Set cancioneses) {
		this.cancioneses = cancioneses;
	}

}
