package model;
// Generated 26 dic 2023 12:32:17 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Playlists generated by hbm2java
 */
public class Playlists implements java.io.Serializable {

	private Integer idPlaylist;
	private Usuarios usuarios;
	private String nombrePlaylist;
	private Set cancioneses = new HashSet(0);

	public Playlists() {
	}

	public Playlists(Usuarios usuarios, String nombrePlaylist, Set cancioneses) {
		this.usuarios = usuarios;
		this.nombrePlaylist = nombrePlaylist;
		this.cancioneses = cancioneses;
	}

	public Integer getIdPlaylist() {
		return this.idPlaylist;
	}

	public void setIdPlaylist(Integer idPlaylist) {
		this.idPlaylist = idPlaylist;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombrePlaylist() {
		return this.nombrePlaylist;
	}

	public void setNombrePlaylist(String nombrePlaylist) {
		this.nombrePlaylist = nombrePlaylist;
	}

	public Set getCancioneses() {
		return this.cancioneses;
	}

	public void setCancioneses(Set cancioneses) {
		this.cancioneses = cancioneses;
	}

}
