package model;
// Generated 26 dic 2023 12:32:17 by Hibernate Tools 6.3.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer idUsuario;
	private String nombreUsuario;
	private String passwrd;
	private String email;
	private Timestamp ultimaConexion;
	private String nombre;
	private String apellidos;
	private Set cancioneses = new HashSet(0);
	private Set playlistses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String nombreUsuario, String passwrd, String email, Timestamp ultimaConexion, String nombre,
			String apellidos, Set cancioneses, Set playlistses) {
		this.nombreUsuario = nombreUsuario;
		this.passwrd = passwrd;
		this.email = email;
		this.ultimaConexion = ultimaConexion;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.cancioneses = cancioneses;
		this.playlistses = playlistses;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNombreUsuario() {
		return this.nombreUsuario;
	}

	public void setNombreUsuario(String nombreUsuario) {
		this.nombreUsuario = nombreUsuario;
	}

	public String getPasswrd() {
		return this.passwrd;
	}

	public void setPasswrd(String passwrd) {
		this.passwrd = passwrd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Timestamp getUltimaConexion() {
		return this.ultimaConexion;
	}

	public void setUltimaConexion(Timestamp ultimaConexion) {
		this.ultimaConexion = ultimaConexion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getCancioneses() {
		return this.cancioneses;
	}

	public void setCancioneses(Set cancioneses) {
		this.cancioneses = cancioneses;
	}

	public Set getPlaylistses() {
		return this.playlistses;
	}

	public void setPlaylistses(Set playlistses) {
		this.playlistses = playlistses;
	}

}
