/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class AnadirCancionAPlaylist extends javax.swing.JPanel {

    /** Creates new form AnadirCancionAPlaylist */
    public AnadirCancionAPlaylist() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoAnadirCancionAPlaylist = new javax.swing.JPanel();
        labelBiblioteca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelLista = new javax.swing.JLabel();
        labelAnadirCancion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        nombreCancion = new javax.swing.JTextField();
        guardarCancion = new javax.swing.JButton();

        fondoAnadirCancionAPlaylist.setBackground(new java.awt.Color(244, 246, 248));

        labelBiblioteca.setForeground(new java.awt.Color(153, 153, 153));
        labelBiblioteca.setText("Biblioteca");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mayor.png"))); // NOI18N

        labelLista.setForeground(new java.awt.Color(153, 153, 153));
        labelLista.setText("Playlist");

        labelAnadirCancion.setText("Añadir Canción");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mayor.png"))); // NOI18N

        labelNombre.setText("Nombre de la canción");

        nombreCancion.setBackground(new java.awt.Color(244, 246, 248));
        nombreCancion.setPreferredSize(new java.awt.Dimension(340, 38));

        guardarCancion.setBackground(new java.awt.Color(139, 243, 204));
        guardarCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guardarCancion.setText("Guardar Canción");
        guardarCancion.setPreferredSize(new java.awt.Dimension(162, 46));

        javax.swing.GroupLayout fondoAnadirCancionAPlaylistLayout = new javax.swing.GroupLayout(fondoAnadirCancionAPlaylist);
        fondoAnadirCancionAPlaylist.setLayout(fondoAnadirCancionAPlaylistLayout);
        fondoAnadirCancionAPlaylistLayout.setHorizontalGroup(
            fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addComponent(labelBiblioteca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(labelLista)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(labelAnadirCancion))
                    .addComponent(labelNombre)
                    .addComponent(nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(604, Short.MAX_VALUE))
        );
        fondoAnadirCancionAPlaylistLayout.setVerticalGroup(
            fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelBiblioteca)
                        .addGap(61, 61, 61)
                        .addComponent(labelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelLista))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelAnadirCancion)))
                .addGap(162, 162, 162)
                .addComponent(guardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoAnadirCancionAPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoAnadirCancionAPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoAnadirCancionAPlaylist;
    private javax.swing.JButton guardarCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAnadirCancion;
    private javax.swing.JLabel labelBiblioteca;
    private javax.swing.JLabel labelLista;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTextField nombreCancion;
    // End of variables declaration//GEN-END:variables

}
