/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

import com.formdev.flatlaf.FlatClientProperties;
import controller.PrincipalController;
import java.awt.Color;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class AnadirCancion1 extends javax.swing.JPanel {
private PrincipalController principalController;
    public AnadirCancion1(PrincipalController principalController) {
        initComponents();
        this.principalController = principalController;
        labelBiblioteca.putClientProperty( "FlatLaf.styleClass", "h1" );
        labelLista.putClientProperty( "FlatLaf.styleClass", "h1" );
        labelAnadirCancion.putClientProperty( "FlatLaf.styleClass", "h1" );
        artista.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "Selena Gomez" ); //Placeholder
        nombreCancion.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "Who Says" ); //Placeholder
        idCancion.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "0001" ); //Placeholder
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoAnadirCancionAPlaylist = new javax.swing.JPanel();
        labelBiblioteca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelLista = new javax.swing.JLabel();
        labelAnadirCancion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        nombreCancion = new javax.swing.JTextField();
        guardarCancion = new javax.swing.JButton();
        idCancion = new javax.swing.JTextField();
        labelNombre1 = new javax.swing.JLabel();
        artista = new javax.swing.JTextField();
        labelNombre2 = new javax.swing.JLabel();
        labelNombre3 = new javax.swing.JLabel();
        playlist = new javax.swing.JComboBox<>();

        fondoAnadirCancionAPlaylist.setBackground(new java.awt.Color(244, 246, 248));

        labelBiblioteca.setForeground(new java.awt.Color(153, 153, 153));
        labelBiblioteca.setText("Biblioteca");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mayor.png"))); // NOI18N

        labelLista.setForeground(new java.awt.Color(153, 153, 153));
        labelLista.setText("Lista de Canciones");
        labelLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelListaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelListaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelListaMouseExited(evt);
            }
        });

        labelAnadirCancion.setText("Añadir Canción");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mayor.png"))); // NOI18N

        labelNombre.setText("Nombre de la canción");

        nombreCancion.setBackground(new java.awt.Color(244, 246, 248));
        nombreCancion.setPreferredSize(new java.awt.Dimension(340, 38));

        guardarCancion.setBackground(new java.awt.Color(139, 243, 204));
        guardarCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guardarCancion.setText("Guardar Canción");
        guardarCancion.setPreferredSize(new java.awt.Dimension(162, 46));

        idCancion.setBackground(new java.awt.Color(244, 246, 248));
        idCancion.setPreferredSize(new java.awt.Dimension(340, 38));

        labelNombre1.setText("ID de la canción");

        artista.setBackground(new java.awt.Color(244, 246, 248));
        artista.setPreferredSize(new java.awt.Dimension(340, 38));

        labelNombre2.setText("Artista");

        labelNombre3.setText("Playlist (Opcional)");

        playlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        playlist.setPreferredSize(new java.awt.Dimension(340, 38));

        javax.swing.GroupLayout fondoAnadirCancionAPlaylistLayout = new javax.swing.GroupLayout(fondoAnadirCancionAPlaylist);
        fondoAnadirCancionAPlaylist.setLayout(fondoAnadirCancionAPlaylistLayout);
        fondoAnadirCancionAPlaylistLayout.setHorizontalGroup(
            fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                                .addComponent(labelBiblioteca)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(labelLista)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addComponent(labelAnadirCancion)))
                        .addContainerGap(647, Short.MAX_VALUE))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre3)
                            .addComponent(playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre1)
                            .addComponent(idCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre2)
                            .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))))
        );
        fondoAnadirCancionAPlaylistLayout.setVerticalGroup(
            fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelBiblioteca)
                        .addGap(61, 61, 61)
                        .addComponent(labelNombre)
                        .addGap(18, 18, 18)
                        .addComponent(nombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelLista))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelAnadirCancion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoAnadirCancionAPlaylistLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNombre1)
                        .addGap(18, 18, 18)
                        .addComponent(idCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre2)
                    .addComponent(labelNombre3))
                .addGap(18, 18, 18)
                .addGroup(fondoAnadirCancionAPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(guardarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoAnadirCancionAPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoAnadirCancionAPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListaMouseClicked
        principalController.mostrarListaDeCanciones();
    }//GEN-LAST:event_labelListaMouseClicked

    private void labelListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListaMouseEntered
        labelLista.setForeground(Color.black);
    }//GEN-LAST:event_labelListaMouseEntered

    private void labelListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelListaMouseExited
        labelLista.setForeground(Color.GRAY);
    }//GEN-LAST:event_labelListaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artista;
    private javax.swing.JPanel fondoAnadirCancionAPlaylist;
    private javax.swing.JButton guardarCancion;
    private javax.swing.JTextField idCancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAnadirCancion;
    private javax.swing.JLabel labelBiblioteca;
    private javax.swing.JLabel labelLista;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JTextField nombreCancion;
    private javax.swing.JComboBox<String> playlist;
    // End of variables declaration//GEN-END:variables

}
