/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.HibernateHelper;
import controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class ChangePassword extends javax.swing.JPanel {
    private HibernateHelper hibernateHelper;
    private String correoRecuperacion;
    private LoginController loginController;        
    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(Interfaz interfaz, String correoRecuperacion, LoginController loginController) {
        initComponents();
        this.correoRecuperacion = correoRecuperacion; // Guarda el correo recuperado en esta clase
        hibernateHelper = new HibernateHelper(); // Inicializa HibernateHelper
        this.loginController = loginController; // Inicializa el loginController
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoChangePassword = new javax.swing.JPanel();
        newPass = new javax.swing.JTextField();
        newPass1 = new javax.swing.JTextField();
        modificarPass = new javax.swing.JButton();
        imagelogin = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();
        inicioLabel = new javax.swing.JLabel();

        fondoChangePassword.setBackground(new java.awt.Color(139, 243, 204));

        newPass.setPreferredSize(new java.awt.Dimension(575, 47));

        newPass1.setPreferredSize(new java.awt.Dimension(575, 47));

        modificarPass.setText("Modificar");
        modificarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPassActionPerformed(evt);
            }
        });

        imagelogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notamusical1.png"))); // NOI18N

        changeLabel.setText("Cambia tu contraseña");

        inicioLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio (1).png"))); // NOI18N
        inicioLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoChangePasswordLayout = new javax.swing.GroupLayout(fondoChangePassword);
        fondoChangePassword.setLayout(fondoChangePasswordLayout);
        fondoChangePasswordLayout.setHorizontalGroup(
            fondoChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                .addGroup(fondoChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(fondoChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(modificarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(changeLabel))
                    .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(inicioLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(imagelogin)
                .addGap(48, 48, 48))
        );
        fondoChangePasswordLayout.setVerticalGroup(
            fondoChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                .addGroup(fondoChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(changeLabel)
                        .addGap(46, 46, 46)
                        .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(newPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(modificarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(inicioLabel))
                    .addGroup(fondoChangePasswordLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(imagelogin)))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPassActionPerformed
        String newPassword = newPass.getText();
        String confirmPassword = newPass1.getText();

        if (newPassword.equals(confirmPassword)) {
            try {
                // Actualiza la contraseña para el correo recuperado
                hibernateHelper.actualizarPasswordPorCorreo(correoRecuperacion, newPassword);
                JOptionPane.showMessageDialog(
                    null,
                    "Contraseña cambiada exitosamente.",
                    "Cambio Exitoso",
                    JOptionPane.INFORMATION_MESSAGE
                );
                // Realiza alguna acción adicional si es necesario después del cambio de contraseña
            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                    null,
                    "Hubo un problema al cambiar la contraseña. Por favor, intenta de nuevo.",
                    "Error al Cambiar Contraseña",
                    JOptionPane.ERROR_MESSAGE
                );
                e.printStackTrace(); // Maneja el error adecuadamente
            }
        } else {
            JOptionPane.showMessageDialog(
                null,
                "Las contraseñas no coinciden. Por favor, verifica.",
                "Error de Coincidencia",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_modificarPassActionPerformed

    private void inicioLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioLabelMouseClicked
       loginController.mostrarLogin();
    }//GEN-LAST:event_inicioLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeLabel;
    private javax.swing.JPanel fondoChangePassword;
    private javax.swing.JLabel imagelogin;
    private javax.swing.JLabel inicioLabel;
    private javax.swing.JButton modificarPass;
    private javax.swing.JTextField newPass;
    private javax.swing.JTextField newPass1;
    // End of variables declaration//GEN-END:variables
}
