/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        //Tamaños
        jLabelInicio.putClientProperty( "FlatLaf.styleClass", "h1" );
        jLabelDescripcion.putClientProperty( "FlatLaf.styleClass", "h3" );
        labelBiblioteca.putClientProperty( "FlatLaf.styleClass", "h3" );
        labelIrABiblioteca.putClientProperty( "FlatLaf.styleClass", "h4" );
        labelArtistas.putClientProperty( "FlatLaf.styleClass", "h3" );
        labelIrAArtistas.putClientProperty( "FlatLaf.styleClass", "h4" );
        labelNumTotalCanciones.putClientProperty( "FlatLaf.styleClass", "h3" );
        labelTusPlaylists.putClientProperty( "FlatLaf.styleClass", "h3" );
        numTodasLasCanciones.putClientProperty( "FlatLaf.styleClass", "h3" );
        numTusPlaylists.putClientProperty( "FlatLaf.styleClass", "h3" );
        labelNumArtistas.putClientProperty( "FlatLaf.styleClass", "h3" );
        labelNumCancionesArtistas.putClientProperty( "FlatLaf.styleClass", "h3" );
        numTotalArtistas.putClientProperty( "FlatLaf.styleClass", "h3" );
        numCancionesArtista.putClientProperty( "FlatLaf.styleClass", "h3" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        panelLibrary = new javax.swing.JPanel();
        labelBiblioteca = new javax.swing.JLabel();
        labelIrABiblioteca = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        numTodasLasCanciones = new javax.swing.JLabel();
        labelNumTotalCanciones = new javax.swing.JLabel();
        labelTusPlaylists = new javax.swing.JLabel();
        numTusPlaylists = new javax.swing.JLabel();
        panelArtists = new javax.swing.JPanel();
        labelArtistas = new javax.swing.JLabel();
        labelIrAArtistas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelNumArtistas = new javax.swing.JLabel();
        labelNumCancionesArtistas = new javax.swing.JLabel();
        numTotalArtistas = new javax.swing.JLabel();
        numCancionesArtista = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaCanciones = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(244, 246, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(1023, 660));

        jLabelInicio.setText("Inicio");

        jLabelDescripcion.setText("Un vistazo rápido a la biblioteca");

        panelLibrary.setBackground(new java.awt.Color(255, 255, 255));
        panelLibrary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 243, 204), 2, true));
        panelLibrary.setPreferredSize(new java.awt.Dimension(456, 140));

        labelBiblioteca.setText("Biblioteca");

        labelIrABiblioteca.setText("Ir a la bilioteca");

        jSeparator1.setForeground(new java.awt.Color(139, 243, 204));

        numTodasLasCanciones.setText("0");

        labelNumTotalCanciones.setText("Número total de canciones guardadas");

        labelTusPlaylists.setText("Tus Playlists");

        numTusPlaylists.setText("0");

        javax.swing.GroupLayout panelLibraryLayout = new javax.swing.GroupLayout(panelLibrary);
        panelLibrary.setLayout(panelLibraryLayout);
        panelLibraryLayout.setHorizontalGroup(
            panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelLibraryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIrABiblioteca)
                .addContainerGap())
            .addGroup(panelLibraryLayout.createSequentialGroup()
                .addGroup(panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibraryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNumTotalCanciones))
                    .addGroup(panelLibraryLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(numTodasLasCanciones)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTusPlaylists)
                    .addGroup(panelLibraryLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(numTusPlaylists)))
                .addGap(49, 49, 49))
        );
        panelLibraryLayout.setVerticalGroup(
            panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibraryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBiblioteca)
                    .addComponent(labelIrABiblioteca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTodasLasCanciones)
                    .addComponent(numTusPlaylists))
                .addGap(18, 18, 18)
                .addGroup(panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumTotalCanciones)
                    .addComponent(labelTusPlaylists))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panelArtists.setBackground(new java.awt.Color(255, 255, 255));
        panelArtists.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(139, 243, 204), 2, true));
        panelArtists.setPreferredSize(new java.awt.Dimension(456, 140));

        labelArtistas.setText("Artistas");

        labelIrAArtistas.setText("Ir a Artistas");

        jSeparator2.setForeground(new java.awt.Color(139, 243, 204));

        labelNumArtistas.setText("Número total de Artistas");

        labelNumCancionesArtistas.setText("Número de canciones");

        numTotalArtistas.setText("0");

        numCancionesArtista.setText("0");

        javax.swing.GroupLayout panelArtistsLayout = new javax.swing.GroupLayout(panelArtists);
        panelArtists.setLayout(panelArtistsLayout);
        panelArtistsLayout.setHorizontalGroup(
            panelArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(panelArtistsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArtistsLayout.createSequentialGroup()
                        .addComponent(labelArtistas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIrAArtistas)
                        .addContainerGap())
                    .addGroup(panelArtistsLayout.createSequentialGroup()
                        .addComponent(labelNumArtistas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(labelNumCancionesArtistas)
                        .addGap(49, 49, 49))))
            .addGroup(panelArtistsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(numTotalArtistas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numCancionesArtista)
                .addGap(106, 106, 106))
        );
        panelArtistsLayout.setVerticalGroup(
            panelArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtistsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArtistas)
                    .addComponent(labelIrAArtistas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTotalArtistas)
                    .addComponent(numCancionesArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelArtistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumArtistas)
                    .addComponent(labelNumCancionesArtistas))
                .addGap(34, 34, 34))
        );

        jLabel7.setText("Lista Completa de Canciones");

        tablaListaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Canción", "ID", "Artista"
            }
        ));
        tablaListaCanciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaListaCanciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(panelArtists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelDescripcion)
                            .addComponent(jLabelInicio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescripcion)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelArtists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelArtistas;
    private javax.swing.JLabel labelBiblioteca;
    private javax.swing.JLabel labelIrAArtistas;
    private javax.swing.JLabel labelIrABiblioteca;
    private javax.swing.JLabel labelNumArtistas;
    private javax.swing.JLabel labelNumCancionesArtistas;
    private javax.swing.JLabel labelNumTotalCanciones;
    private javax.swing.JLabel labelTusPlaylists;
    private javax.swing.JLabel numCancionesArtista;
    private javax.swing.JLabel numTodasLasCanciones;
    private javax.swing.JLabel numTotalArtistas;
    private javax.swing.JLabel numTusPlaylists;
    private javax.swing.JPanel panelArtists;
    private javax.swing.JPanel panelLibrary;
    private javax.swing.JTable tablaListaCanciones;
    // End of variables declaration//GEN-END:variables
}
