/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import controller.LoginController;
import javax.swing.JPanel;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class Interfaz extends javax.swing.JFrame {

    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        LoginController loginController = new LoginController(this);
        loginController.mostrarLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ponerPaneles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ponerPanelesLayout = new javax.swing.GroupLayout(ponerPaneles);
        ponerPaneles.setLayout(ponerPanelesLayout);
        ponerPanelesLayout.setHorizontalGroup(
            ponerPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        ponerPanelesLayout.setVerticalGroup(
            ponerPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ponerPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ponerPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightFlatIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ponerPaneles;
    // End of variables declaration//GEN-END:variables
    // Método mostrarPanel para mostrar los paneles.
    public void mostrarPanel(JPanel p) {
        p.setSize(1280, 720); //Se pone el tamaño con el que se mostrarán
        p.setLocation(0,0); // Se establece la posición de la ventana en las coordenadas (0, 0).
        
        ponerPaneles.removeAll(); // Elimina todos los componentes hijos del panel para que no haya nada al mostrar el panel que se quiere
        ponerPaneles.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)); // Se especifican las coordenadas y el tamaño del componente.
        ponerPaneles.revalidate(); // Obliga al panel a recalcular su diseño.
        ponerPaneles.repaint(); // Solicita al panel que repinte sus componentes. 
    }
    
    public void mostrarDashboard(int idUsuario) {
        Principal dashboard = new Principal(idUsuario);
        mostrarPanel(dashboard);
    }
}
