/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatClientProperties;

/**
 *
 * @author Alumno
 */
public class ListaDeCanciones extends javax.swing.JPanel {

    /**
     * Creates new form ListaDeCanciones
     */
    public ListaDeCanciones() {
        initComponents();
        labelBiblioteca.putClientProperty( "FlatLaf.styleClass", "h1" );
        labelLista.putClientProperty( "FlatLaf.styleClass", "h1" );
        labelDescripcion.putClientProperty( "FlatLaf.styleClass", "h4" );
        buscarCancion.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "Busca una Canción" ); //Placeholder
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoLista = new javax.swing.JPanel();
        labelBiblioteca = new javax.swing.JLabel();
        labelLista = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        buscarCancion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCanciones = new javax.swing.JTable();
        borrarCancion = new javax.swing.JButton();
        AnadirCancion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        fondoLista.setBackground(new java.awt.Color(244, 246, 248));

        labelBiblioteca.setForeground(new java.awt.Color(153, 153, 153));
        labelBiblioteca.setText("Biblioteca");

        labelLista.setText("Lista de Canciones");

        labelDescripcion.setText("Lista de canciones que has guardado");

        buscarCancion.setBackground(new java.awt.Color(244, 246, 248));
        buscarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        buscarCancion.setPreferredSize(new java.awt.Dimension(340, 38));

        tablaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Canción", "ID", "Playlist", "Artista"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCanciones.setMinimumSize(new java.awt.Dimension(944, 438));
        tablaCanciones.setPreferredSize(new java.awt.Dimension(944, 438));
        jScrollPane1.setViewportView(tablaCanciones);
        if (tablaCanciones.getColumnModel().getColumnCount() > 0) {
            tablaCanciones.getColumnModel().getColumn(0).setResizable(false);
            tablaCanciones.getColumnModel().getColumn(1).setResizable(false);
            tablaCanciones.getColumnModel().getColumn(3).setResizable(false);
        }

        borrarCancion.setBackground(new java.awt.Color(139, 243, 204));
        borrarCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        borrarCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mas.png"))); // NOI18N
        borrarCancion.setText("Borrar Canción");
        borrarCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AnadirCancion.setBackground(new java.awt.Color(139, 243, 204));
        AnadirCancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AnadirCancion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mas.png"))); // NOI18N
        AnadirCancion.setText("Añadir Canción");
        AnadirCancion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mayor.png"))); // NOI18N

        javax.swing.GroupLayout fondoListaLayout = new javax.swing.GroupLayout(fondoLista);
        fondoLista.setLayout(fondoListaLayout);
        fondoListaLayout.setHorizontalGroup(
            fondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoListaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(fondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fondoListaLayout.createSequentialGroup()
                        .addComponent(labelBiblioteca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(labelLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(AnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDescripcion)
                    .addComponent(buscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        fondoListaLayout.setVerticalGroup(
            fondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoListaLayout.createSequentialGroup()
                .addGroup(fondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoListaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labelBiblioteca))
                    .addGroup(fondoListaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(fondoListaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(fondoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLista)
                            .addComponent(AnadirCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(labelDescripcion)
                .addGap(16, 16, 16)
                .addComponent(buscarCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnadirCancion;
    private javax.swing.JButton borrarCancion;
    private javax.swing.JTextField buscarCancion;
    private javax.swing.JPanel fondoLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBiblioteca;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelLista;
    private javax.swing.JTable tablaCanciones;
    // End of variables declaration//GEN-END:variables
}
