/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class PlaylistCreada extends javax.swing.JPanel {

    /**
     * Creates new form PlaylistCreada
     */
    public PlaylistCreada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPlaylistsCreada = new javax.swing.JPanel();
        labelBiblioteca = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelPlaylists = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        buscarPlaylist = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlaylistDetallada = new javax.swing.JTable();
        anadirCancionAPlaylist = new javax.swing.JButton();

        fondoPlaylistsCreada.setBackground(new java.awt.Color(244, 246, 248));

        labelBiblioteca.setForeground(new java.awt.Color(153, 153, 153));
        labelBiblioteca.setText("Biblioteca");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mayor.png"))); // NOI18N

        labelPlaylists.setText("Playlists");

        labelDescripcion.setText("Vista detallada de una Playlist");

        buscarPlaylist.setBackground(new java.awt.Color(227, 236, 227));
        buscarPlaylist.setPreferredSize(new java.awt.Dimension(340, 38));

        tablaPlaylistDetallada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Canción", "Artista", "Acción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPlaylistDetallada);

        anadirCancionAPlaylist.setBackground(new java.awt.Color(139, 243, 204));
        anadirCancionAPlaylist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anadirCancionAPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mas.png"))); // NOI18N
        anadirCancionAPlaylist.setText("Añadir Canción");
        anadirCancionAPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout fondoPlaylistsCreadaLayout = new javax.swing.GroupLayout(fondoPlaylistsCreada);
        fondoPlaylistsCreada.setLayout(fondoPlaylistsCreadaLayout);
        fondoPlaylistsCreadaLayout.setHorizontalGroup(
            fondoPlaylistsCreadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPlaylistsCreadaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(fondoPlaylistsCreadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescripcion)
                    .addGroup(fondoPlaylistsCreadaLayout.createSequentialGroup()
                        .addComponent(labelBiblioteca)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(labelPlaylists)
                        .addGap(583, 583, 583)
                        .addComponent(anadirCancionAPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        fondoPlaylistsCreadaLayout.setVerticalGroup(
            fondoPlaylistsCreadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPlaylistsCreadaLayout.createSequentialGroup()
                .addGroup(fondoPlaylistsCreadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoPlaylistsCreadaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(fondoPlaylistsCreadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPlaylists)
                            .addComponent(anadirCancionAPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBiblioteca))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoPlaylistsCreadaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)))
                .addComponent(labelDescripcion)
                .addGap(18, 18, 18)
                .addComponent(buscarPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPlaylistsCreada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPlaylistsCreada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirCancionAPlaylist;
    private javax.swing.JTextField buscarPlaylist;
    private javax.swing.JPanel fondoPlaylistsCreada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBiblioteca;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelPlaylists;
    private javax.swing.JTable tablaPlaylistDetallada;
    // End of variables declaration//GEN-END:variables
}
