/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import controller.HibernateHelper;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Usuarios;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class Principal extends javax.swing.JPanel {
    private HibernateHelper sqlHelper;
    private int idUsuario;
    /**
     * Creates new form Dashboard
     */
    public Principal(int idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
        sqlHelper = new HibernateHelper();
        //numCanciones.setText(String.valueOf(obtenerNumeroCanciones())); // Actualizar el JLabel con el número de canciones
        
        iconDash.setIcon(new FlatSVGIcon("img/Dashboard.svg"));
        iconLib.setIcon(new FlatSVGIcon("img/Library.svg"));
        iconArt.setIcon(new FlatSVGIcon("img/Artist.svg"));
        iconOut.setIcon(new FlatSVGIcon("img/Logout.svg"));
        
        mostrarPanel(new Inicio()); // Mostrar el panel 'Inicio' al inicializar la clase Principal
    }
    
    public void mostrarPanel(JPanel p) {
        p.setSize(1042, 720); // Establecer el tamaño del panel 'p'
        p.setLocation(0, 0); // Establecer la posición del panel 'p'
        
        colocarPaneles.removeAll(); // Eliminar todos los componentes del panel colocarPaneles
        colocarPaneles.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)); // Agregar el panel 'p' a colocarPaneles
        colocarPaneles.revalidate(); // Recalcular el diseño del panel colocarPaneles
        colocarPaneles.repaint(); // Repintar los componentes del panel colocarPaneles
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoDashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelLibrary = new javax.swing.JPanel();
        jLabelLibrary = new javax.swing.JLabel();
        iconLib = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        panelDashboard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        iconDash = new javax.swing.JLabel();
        panelArtist = new javax.swing.JPanel();
        jLabelArtist = new javax.swing.JLabel();
        iconArt = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        jLabelLogout = new javax.swing.JLabel();
        iconOut = new javax.swing.JLabel();
        colocarPaneles = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(79, 52, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(57, 37, 65));
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notamusical2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelLibrary.setBackground(new java.awt.Color(102, 0, 102));
        panelLibrary.setPreferredSize(new java.awt.Dimension(256, 46));

        jLabelLibrary.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLibrary.setText("Library");

        javax.swing.GroupLayout panelLibraryLayout = new javax.swing.GroupLayout(panelLibrary);
        panelLibrary.setLayout(panelLibraryLayout);
        panelLibraryLayout.setHorizontalGroup(
            panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibraryLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconLib)
                .addGap(26, 26, 26)
                .addComponent(jLabelLibrary)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        panelLibraryLayout.setVerticalGroup(
            panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibraryLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelLibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLib, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLibrary))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username");
        jPanel1.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 95, -1, -1));

        panelDashboard.setBackground(new java.awt.Color(102, 0, 102));
        panelDashboard.setPreferredSize(new java.awt.Dimension(256, 46));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconDash)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconDash, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, -1, -1));

        panelArtist.setBackground(new java.awt.Color(102, 0, 102));
        panelArtist.setPreferredSize(new java.awt.Dimension(256, 46));

        jLabelArtist.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArtist.setText("Autor");

        javax.swing.GroupLayout panelArtistLayout = new javax.swing.GroupLayout(panelArtist);
        panelArtist.setLayout(panelArtistLayout);
        panelArtistLayout.setHorizontalGroup(
            panelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtistLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconArt)
                .addGap(26, 26, 26)
                .addComponent(jLabelArtist)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        panelArtistLayout.setVerticalGroup(
            panelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtistLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelArtistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelArtist))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelArtist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        panelLogout.setBackground(new java.awt.Color(102, 0, 102));
        panelLogout.setPreferredSize(new java.awt.Dimension(256, 46));

        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setText("Log Out");

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconOut)
                .addGap(26, 26, 26)
                .addComponent(jLabelLogout)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconOut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLogout))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        colocarPaneles.setBackground(new java.awt.Color(204, 255, 204));
        colocarPaneles.setPreferredSize(new java.awt.Dimension(1042, 720));

        javax.swing.GroupLayout colocarPanelesLayout = new javax.swing.GroupLayout(colocarPaneles);
        colocarPaneles.setLayout(colocarPanelesLayout);
        colocarPanelesLayout.setHorizontalGroup(
            colocarPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1042, Short.MAX_VALUE)
        );
        colocarPanelesLayout.setVerticalGroup(
            colocarPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoDashboardLayout = new javax.swing.GroupLayout(fondoDashboard);
        fondoDashboard.setLayout(fondoDashboardLayout);
        fondoDashboardLayout.setHorizontalGroup(
            fondoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoDashboardLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(colocarPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoDashboardLayout.setVerticalGroup(
            fondoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(colocarPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colocarPaneles;
    private javax.swing.JPanel fondoDashboard;
    private javax.swing.JLabel iconArt;
    private javax.swing.JLabel iconDash;
    private javax.swing.JLabel iconLib;
    private javax.swing.JLabel iconOut;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelLibrary;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelArtist;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelLibrary;
    private javax.swing.JPanel panelLogout;
    // End of variables declaration//GEN-END:variables
}
