/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
//Placeholer para primera entrega
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import controller.HibernateHelper;
import controller.LoginController;
import controller.PrincipalController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Usuarios;

/**
 *
 * @author Carlos de los Dolores Macías
 */
public class Principal extends javax.swing.JPanel {
    private PrincipalController principalController;
    private HibernateHelper sqlHelper;
    private int idUsuario;
    Color colorSeleccion = new Color(185, 253, 228); //Color al entrar en los paneles
    Color colorSeleccion2 = new Color(139,243,204); //Color al salir de los paneles
    Color colorSeleccion3 = new Color(23,205,137); //Color al salir de los paneles
    
    // Variable para controlar el estado de visibilidad del panel desplegable de la biblioteca
    private boolean bibliotecaDesplegada = false;
    
    /**
     * 
     * @param idUsuario este argumento es el id del usuario
     */
    public Principal(int idUsuario) {
        initComponents();
        principalController = new PrincipalController(this);
        this.idUsuario = idUsuario;
        sqlHelper = new HibernateHelper();
        //numCanciones.setText(String.valueOf(obtenerNumeroCanciones())); // Actualizar el JLabel con el número de canciones
        
        iconDash.setIcon(new FlatSVGIcon("img/Dashboard.svg"));
        iconLib.setIcon(new FlatSVGIcon("img/biblio.svg"));
        iconArt1.setIcon(new FlatSVGIcon("img/Artist.svg"));
        iconOut1.setIcon(new FlatSVGIcon("img/Logout.svg"));
        iconDesplegable.setIcon(new FlatSVGIcon("img/flechaAbajo.svg"));
        textFieldBusqueda.putClientProperty( FlatClientProperties.TEXT_FIELD_TRAILING_ICON,
                new FlatSVGIcon( "img/Lupa.svg" ) );
        textFieldBusqueda.putClientProperty( FlatClientProperties.PLACEHOLDER_TEXT, "Busca algo aquí" ); //Placeholder
        textFieldBusqueda.putClientProperty( "FlatLaf.style", "arc:10"); //Redondeo
        
        mostrarPanel(new Inicio()); // Mostrar el panel 'Inicio' al inicializar la clase Principal
        panelDesplegable.setVisible(false); //Por defecto se oculta el panelDesplegable
        
        //Tamaños
        labelMusicNocta.putClientProperty( "FlatLaf.styleClass", "h1" );
        jLabelUsername.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelInicio.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelBiblioteca.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelInicio.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelLista.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelArtist.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelPlaylists.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelCerrarSesion.putClientProperty( "FlatLaf.styleClass", "h3" );
        jLabelBuenos.putClientProperty( "FlatLaf.styleClass", "h3" );
    }
    
    /**
     * Método para mostrar los paneles.
     * @param p este argumento es el panel que se quiera mostrar
     */
    public void mostrarPanel(JPanel p) {
        colocarPaneles.removeAll(); // Elimina todos los componentes hijos del panel para que no haya nada al mostrar el panel que se quiere
        colocarPaneles.setLayout(new BorderLayout()); // Establece el BorderLayout para que el panel se expanda

        colocarPaneles.add(p, BorderLayout.CENTER); // Agrega el panel al centro para que se ajuste al tamaño del contenedor

        colocarPaneles.revalidate(); // Obliga al panel a recalcular su diseño
        colocarPaneles.repaint(); // Solicita al panel que repinte sus componentes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoDashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelMusicNocta = new javax.swing.JLabel();
        imgApp = new javax.swing.JLabel();
        panelBiblioteca = new javax.swing.JPanel();
        jLabelBiblioteca = new javax.swing.JLabel();
        iconDesplegable = new javax.swing.JLabel();
        iconLib = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        panelInicio = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        iconDash = new javax.swing.JLabel();
        panelCerrarSesion = new javax.swing.JPanel();
        jLabelCerrarSesion = new javax.swing.JLabel();
        iconOut1 = new javax.swing.JLabel();
        panelArtista = new javax.swing.JPanel();
        jLabelArtist = new javax.swing.JLabel();
        iconArt1 = new javax.swing.JLabel();
        panelDesplegable = new javax.swing.JPanel();
        panelListaCanciones = new javax.swing.JPanel();
        jLabelLista = new javax.swing.JLabel();
        iconArt = new javax.swing.JLabel();
        panelPlaylists = new javax.swing.JPanel();
        jLabelPlaylists = new javax.swing.JLabel();
        iconOut = new javax.swing.JLabel();
        colocarPaneles = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        textFieldBusqueda = new javax.swing.JTextField();
        jLabelBuenos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 0));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(139, 243, 204));

        jPanel2.setBackground(new java.awt.Color(23, 205, 137));
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 60));

        labelMusicNocta.setText("Music Nocta");

        imgApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notamusical2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imgApp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelMusicNocta)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelMusicNocta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgApp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelBiblioteca.setBackground(new java.awt.Color(139, 243, 204));
        panelBiblioteca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBiblioteca.setPreferredSize(new java.awt.Dimension(256, 46));
        panelBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelBibliotecaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBibliotecaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBibliotecaMouseExited(evt);
            }
        });

        jLabelBiblioteca.setText("Biblioteca");

        javax.swing.GroupLayout panelBibliotecaLayout = new javax.swing.GroupLayout(panelBiblioteca);
        panelBiblioteca.setLayout(panelBibliotecaLayout);
        panelBibliotecaLayout.setHorizontalGroup(
            panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBibliotecaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(iconLib)
                .addGap(18, 18, 18)
                .addComponent(jLabelBiblioteca)
                .addGap(79, 79, 79)
                .addComponent(iconDesplegable))
        );
        panelBibliotecaLayout.setVerticalGroup(
            panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBibliotecaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBiblioteca)
                        .addComponent(iconLib))
                    .addGroup(panelBibliotecaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(iconDesplegable))))
        );

        jLabelUsername.setText("Username");

        panelInicio.setBackground(new java.awt.Color(139, 243, 204));
        panelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelInicio.setPreferredSize(new java.awt.Dimension(256, 46));
        panelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelInicioMouseExited(evt);
            }
        });

        jLabelInicio.setText("Inicio");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(iconDash)
                .addGap(18, 18, 18)
                .addComponent(jLabelInicio)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInicio)
                    .addComponent(iconDash))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelCerrarSesion.setBackground(new java.awt.Color(139, 243, 204));
        panelCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelCerrarSesion.setPreferredSize(new java.awt.Dimension(256, 46));
        panelCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCerrarSesionMouseExited(evt);
            }
        });

        jLabelCerrarSesion.setText("Log Out");

        javax.swing.GroupLayout panelCerrarSesionLayout = new javax.swing.GroupLayout(panelCerrarSesion);
        panelCerrarSesion.setLayout(panelCerrarSesionLayout);
        panelCerrarSesionLayout.setHorizontalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconOut1)
                .addGap(26, 26, 26)
                .addComponent(jLabelCerrarSesion)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelCerrarSesionLayout.setVerticalGroup(
            panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCerrarSesionLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconOut1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCerrarSesion))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelArtista.setBackground(new java.awt.Color(139, 243, 204));
        panelArtista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelArtista.setPreferredSize(new java.awt.Dimension(256, 46));
        panelArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelArtistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelArtistaMouseExited(evt);
            }
        });

        jLabelArtist.setText("Artista");

        javax.swing.GroupLayout panelArtistaLayout = new javax.swing.GroupLayout(panelArtista);
        panelArtista.setLayout(panelArtistaLayout);
        panelArtistaLayout.setHorizontalGroup(
            panelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtistaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconArt1)
                .addGap(26, 26, 26)
                .addComponent(jLabelArtist)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        panelArtistaLayout.setVerticalGroup(
            panelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtistaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconArt1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelArtist))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelDesplegable.setBackground(new java.awt.Color(23, 205, 137));

        panelListaCanciones.setBackground(new java.awt.Color(23, 205, 137));
        panelListaCanciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelListaCanciones.setPreferredSize(new java.awt.Dimension(256, 46));
        panelListaCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelListaCancionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelListaCancionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelListaCancionesMouseExited(evt);
            }
        });

        jLabelLista.setText("Lista de Canciones");

        javax.swing.GroupLayout panelListaCancionesLayout = new javax.swing.GroupLayout(panelListaCanciones);
        panelListaCanciones.setLayout(panelListaCancionesLayout);
        panelListaCancionesLayout.setHorizontalGroup(
            panelListaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaCancionesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconArt)
                .addGap(26, 26, 26)
                .addComponent(jLabelLista)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panelListaCancionesLayout.setVerticalGroup(
            panelListaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaCancionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelListaCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconArt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelLista))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelPlaylists.setBackground(new java.awt.Color(23, 205, 137));
        panelPlaylists.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelPlaylists.setPreferredSize(new java.awt.Dimension(256, 46));
        panelPlaylists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPlaylistsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPlaylistsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPlaylistsMouseExited(evt);
            }
        });

        jLabelPlaylists.setText("Playlists");

        javax.swing.GroupLayout panelPlaylistsLayout = new javax.swing.GroupLayout(panelPlaylists);
        panelPlaylists.setLayout(panelPlaylistsLayout);
        panelPlaylistsLayout.setHorizontalGroup(
            panelPlaylistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlaylistsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iconOut)
                .addGap(26, 26, 26)
                .addComponent(jLabelPlaylists)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelPlaylistsLayout.setVerticalGroup(
            panelPlaylistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlaylistsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelPlaylistsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconOut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPlaylists))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDesplegableLayout = new javax.swing.GroupLayout(panelDesplegable);
        panelDesplegable.setLayout(panelDesplegableLayout);
        panelDesplegableLayout.setHorizontalGroup(
            panelDesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDesplegableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelDesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelListaCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelDesplegableLayout.setVerticalGroup(
            panelDesplegableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDesplegableLayout.createSequentialGroup()
                .addComponent(panelListaCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabelUsername))
                    .addComponent(panelBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDesplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabelUsername)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(panelBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDesplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(panelCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        colocarPaneles.setBackground(new java.awt.Color(244, 246, 248));
        colocarPaneles.setPreferredSize(new java.awt.Dimension(1042, 720));

        javax.swing.GroupLayout colocarPanelesLayout = new javax.swing.GroupLayout(colocarPaneles);
        colocarPaneles.setLayout(colocarPanelesLayout);
        colocarPanelesLayout.setHorizontalGroup(
            colocarPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1023, Short.MAX_VALUE)
        );
        colocarPanelesLayout.setVerticalGroup(
            colocarPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        textFieldBusqueda.setBackground(new java.awt.Color(227, 236, 227));
        textFieldBusqueda.setPreferredSize(new java.awt.Dimension(440, 38));

        jLabelBuenos.setText("Buenos días");

        jLabel2.setText("fecha");

        jLabel3.setText("hora");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelBuenos)
                        .addGap(25, 25, 25)))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelBuenos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(textFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoDashboardLayout = new javax.swing.GroupLayout(fondoDashboard);
        fondoDashboard.setLayout(fondoDashboardLayout);
        fondoDashboardLayout.setHorizontalGroup(
            fondoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoDashboardLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(colocarPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE))
            .addGroup(fondoDashboardLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoDashboardLayout.setVerticalGroup(
            fondoDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fondoDashboardLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(colocarPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBibliotecaMouseClicked
        mostrarPanel(new Biblioteca());
        // Cambia el estado de visibilidad y actualiza los paneles
        bibliotecaDesplegada = !bibliotecaDesplegada;
        actualizarPaneles();
    }//GEN-LAST:event_panelBibliotecaMouseClicked

    private void panelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioMouseClicked
        mostrarPanel(new Inicio());
    }//GEN-LAST:event_panelInicioMouseClicked

    //Eventos para los paneles cuando entra y sale el mouse de ellos (se cambiará el color)
    private void panelInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioMouseEntered
        panelInicio.setBackground(colorSeleccion);
    }//GEN-LAST:event_panelInicioMouseEntered

    private void panelInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInicioMouseExited
        panelInicio.setBackground(colorSeleccion2);
    }//GEN-LAST:event_panelInicioMouseExited

    private void panelBibliotecaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBibliotecaMouseEntered
        panelBiblioteca.setBackground(colorSeleccion);
    }//GEN-LAST:event_panelBibliotecaMouseEntered

    private void panelBibliotecaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBibliotecaMouseExited
        panelBiblioteca.setBackground(colorSeleccion2);
    }//GEN-LAST:event_panelBibliotecaMouseExited

    private void panelListaCancionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListaCancionesMouseExited
        panelListaCanciones.setBackground(colorSeleccion3);
    }//GEN-LAST:event_panelListaCancionesMouseExited

    private void panelListaCancionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListaCancionesMouseEntered
        panelListaCanciones.setBackground(colorSeleccion);
    }//GEN-LAST:event_panelListaCancionesMouseEntered

    private void panelPlaylistsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlaylistsMouseEntered
        panelPlaylists.setBackground(colorSeleccion);
        panelDesplegable.setBackground(colorSeleccion);
    }//GEN-LAST:event_panelPlaylistsMouseEntered

    private void panelPlaylistsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlaylistsMouseExited
        panelPlaylists.setBackground(colorSeleccion3);
        panelDesplegable.setBackground(colorSeleccion3);
    }//GEN-LAST:event_panelPlaylistsMouseExited

    private void panelArtistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelArtistaMouseExited
        panelArtista.setBackground(colorSeleccion2);
    }//GEN-LAST:event_panelArtistaMouseExited

    private void panelCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMouseExited
        panelCerrarSesion.setBackground(colorSeleccion2);
    }//GEN-LAST:event_panelCerrarSesionMouseExited

    private void panelArtistaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelArtistaMouseEntered
        panelArtista.setBackground(colorSeleccion);
    }//GEN-LAST:event_panelArtistaMouseEntered

    private void panelCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCerrarSesionMouseEntered
        panelCerrarSesion.setBackground(colorSeleccion);
    }//GEN-LAST:event_panelCerrarSesionMouseEntered

    private void panelListaCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelListaCancionesMouseClicked
        principalController.mostrarListaDeCanciones();
    }//GEN-LAST:event_panelListaCancionesMouseClicked

    private void panelPlaylistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPlaylistsMouseClicked
        mostrarPanel(new Playlists());
    }//GEN-LAST:event_panelPlaylistsMouseClicked

    private void actualizarPaneles() {
        panelDesplegable.setVisible(bibliotecaDesplegada);

        colocarPaneles.revalidate();
        colocarPaneles.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colocarPaneles;
    private javax.swing.JPanel fondoDashboard;
    private javax.swing.JLabel iconArt;
    private javax.swing.JLabel iconArt1;
    private javax.swing.JLabel iconDash;
    private javax.swing.JLabel iconDesplegable;
    private javax.swing.JLabel iconLib;
    private javax.swing.JLabel iconOut;
    private javax.swing.JLabel iconOut1;
    private javax.swing.JLabel imgApp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelBiblioteca;
    private javax.swing.JLabel jLabelBuenos;
    private javax.swing.JLabel jLabelCerrarSesion;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLista;
    private javax.swing.JLabel jLabelPlaylists;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelMusicNocta;
    private javax.swing.JPanel panelArtista;
    private javax.swing.JPanel panelBiblioteca;
    private javax.swing.JPanel panelCerrarSesion;
    private javax.swing.JPanel panelDesplegable;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelListaCanciones;
    private javax.swing.JPanel panelPlaylists;
    private javax.swing.JTextField textFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
